name: generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: teja <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.32.0
  build: ^0.12.7
  source_gen: ^0.9.0
  annotations:
  meta: ^1.1.5

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.10.0
  build_test: ^0.10.3
  collection: ^1.14.11

dependency_overrides:
  annotations:
    path: ../annotations
